In [12]:
import cv2
import numpy as np
from numpy import ndarray
from matplotlib import pyplot as plt

plt.rcParams['figure.figsize'] = [16, 16]

# path to local images
IMAGE_PARENT_FOLDER = "/Users/chris/Dev/cod_records/aws/extracted/"
IMAGE_TEST_FOLDER = IMAGE_PARENT_FOLDER + "31829_B016711/"

In [20]:
import os

shapes  = []
folders = [x for x in os.scandir(IMAGE_PARENT_FOLDER) if x.is_dir()]

for folder in folders:
    for fp in os.scandir(folder):
        img = cv2.imread(fp)
        shapes.append(img.shape[0])

counts = np.unique(shapes, return_counts=True)
print(counts)

(array([ 596,  599,  600,  604,  605,  606,  607,  608,  609,  610,  611,
        612,  613,  614,  615,  616,  617,  618,  619,  620,  621,  622,
        623,  624,  625,  626,  627,  628,  629,  630,  631,  632,  633,
        634,  635,  636,  637,  638,  639,  640,  641,  642,  643,  644,
        646,  647,  648,  652,  653,  656,  657,  658,  659,  660,  661,
        662,  663,  664,  665,  666,  667,  668,  669,  671,  672,  673,
        674,  675,  676,  677,  678,  679,  680,  681,  682,  683,  684,
        685,  686,  687,  688,  689,  690,  691,  692,  693,  694,  695,
        696,  697,  698,  699,  700,  701,  702,  703,  704,  705,  706,
        707,  708,  709,  710,  711,  712,  713,  714,  715,  716,  717,
        718,  719,  720,  721,  722,  723,  724,  725,  726,  727,  728,
        729,  730,  731,  732,  733,  734,  735,  736,  737,  738,  739,
        740,  741,  744,  746,  747,  748,  750,  751,  752,  753,  756,
        757,  758,  765,  766,  767,  772,  775,  

In [30]:
print(counts[1][:40])

[    2     1     1     1     4     1     3    14    34    35    19    25
    24    96  3540 14662 37978 11750  3389   492   131    86    70    39
    30    28    49    60    58    41    30    48    19    13    13    15
     9    10     9     6]


In [32]:
print(np.sum(counts[1]))

73684


In [39]:
np.sum(counts[1][14:19]) / np.sum(counts[1])

np.float64(0.9679034797242277)

In [40]:
counts[0][14:19]

array([615, 616, 617, 618, 619])

In [41]:
import os

widths  = []
folders = [x for x in os.scandir(IMAGE_PARENT_FOLDER) if x.is_dir()]

for folder in folders:
    for fp in os.scandir(folder):
        img = cv2.imread(fp)
        widths.append(img.shape[1])

w_counts = np.unique(widths, return_counts=True)
print(w_counts)

(array([1200]), array([73684]))
